import type { Metadata } from "next";
import { Dancing_Script, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page1"
import Header from "./Header/page"

const geistSans = Roboto_Mono({
  variable: "--font-techno",
  subsets: ["latin"],
  
});

const geistMono = Roboto_Mono({
  variable: "--font-techno",
  subsets: ["latin"],
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className="font-techno">
        <Header/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}